spring.application.name=TaskVault API

# PostgreSQL Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskvault_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

## JPA/Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET:2XZCFnmx0gac6Obn7LVsXtxpT36eCKJBGEbXg3luFuN2}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Server Configuration
server.servlet.context-path=${SERVER_CONTEXT_PATH:/taskApi/v1.1}
server.port=${SERVER_PORT:8081}

# Springdoc OpenAPI (Swagger)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.show-actuator=false

#flyway
spring.flyway.enabled=true