CREATE TABLE roles
(
    role_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE task
(
    task_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_title       VARCHAR(255),
    task_description VARCHAR(255),
    task_status      VARCHAR(255),
    task_create_at   date,
    task_update_at   date,
    user_id_task     BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (task_id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_username VARCHAR(255),
    user_password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_USER_ID_TASK FOREIGN KEY (user_id_task) REFERENCES users (user_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_users FOREIGN KEY (user_id) REFERENCES users (user_id);